# Generated by Django 4.2.9 on 2024-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.PositiveBigIntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('post_nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField()),
                ('promotion', models.CharField(max_length=50)),
            ],
        ),
    ]
